title: Shopify App CLI
markdown: kramdown
url: https://shopify.github.io
baseurl: /shopify-app-cli

exclude: [
  'heroku/',
  'Gemfile',
  'Gemfile.lock'
]

defaults:
  - scope:
      path: ""
    values:
      toc: true

plugins:
  - jekyll-redirect-from